# Site settings
title: cfbastarz.github.io
url: "https://cfbastarz.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "https://cfbastarz.github.io" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
timezone: America/Sao_Paulo
description: >
  Aqui escrevo sobre problemas binários em geral.

# Your information
email: cfbastarz@gmail.com
author: Carlos Frederico Bastarz
avatar: "https://cfbastarz.github.io/assets/avatar.png"
profile: Are you challenging me?
#twitter_username: twitter_username
#github_username: cfbastarz
profile_links:
  Email: "mailto:cfbastarz@gmail.com"
  GitHub: "https://github.com/cfbastarz"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    Sobre: /about/
    Categorias: /category/

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
