# Site settings
title: Carlos Frederico Bastarz
url: "https://cfbastarz.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
#baseurl: "/cfbastarz" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
timezone: America/Brasilia
description: >
  Página pessoal de Carlos Frederico Bastarz

# Your information
email: cfbastarz@gmail.com
author: Carlos Frederico Bastarz
avatar: "https://s.gravatar.com/avatar/1573e6ecaedd8b5a641dce5d582efd56?s=80"
profile: Eu.
#twitter_username: twitter_username
#github_username:  github_username
profile_links:
  Email: "mailto:cfbastarz@gmail.com"
  GitHub: "https://github.com/cfbastarz"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    Sobre: /about/
    Categorias: /category/
#    Donate: https://laobubu.net/donate.html

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
