# Project information
#site_name: Atas das Reuniões do Comitê Científico do MONAN 
site_name: cfbasz
site_author: Carlos Frederico Bastarz
site_description: Since 1982

# Repository
repo_name: cfbastarz
repo_url: https://github.com/cfbastarz/cfbastarz.github.io
edit_uri: edit/master/docs/

# Page tree
#nav:
#  - Home: index.md
#  - 'Curriculum Vitae': cv.md
#  - Videos: videos.md

# Configuration
theme: 
  name: null
  custom_dir: 'cinder'
  language: pt-BR

extra:
    social:
      - icon: fontawesome/brands/youtube
        link: https://www.youtube.com/channel/UCYl-EgRTESHnSLlpKUxWrrg
      - icon: fontawesome/brands/github
        link: https://github.com/cfbastarz
      - icon: fontawesome/solid/paper-plane
        link: mailto:cfbastarz@gmail.com

# Extensions
markdown_extensions:
  - footnotes
  - tables
  - admonition
  - abbr
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

# Plugins
plugins:
  - mkdocs-video
  - search
  - blog:
      format: "[%y/%m/%d]"
      text-align: "left"
  - awesome-pages
